### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by siberianguy** [tompetko/SignalR.WebSocketSharpTransport#1]
Thanks a lot for sharing this solution. I found it in [CloudFlareUtilities's thread](https://github.com/elcattivo/CloudFlareUtilities/issues/18) and it was extremely helpful.

I need to integrate it into a .NET Core application and I would like to know whether you think it's possible. As I understand current solution depends on full framework versions of both SignalR and Websocket-Sharp. Seems like SignalR could be replaced by a [.NET Core implementation](https://github.com/aspnet/SignalR) buy there's no .NET Core version of Websocket-Sharp, so the only chance is to find the same functionality in another .NET Core  implementation of Web Sockets (i. e. [WebSocket4Net](https://github.com/kerryjiang/WebSocket4Net)).

Would love to know your thoughts on this :)

**Comment by tompetko** [comment]
Hi and thanks! :) I was thinking of this while creating this project, but unfortunatelly, back then, there wasn't any library supporting .NET Core and as far as I know, nothing changed. WebSocket4Net is just a WebSocket library. SignalR is built on top of it and for now, I have no time to do it :) Feel free to create pull request. Anyway, I haven't tested .NET Core SignalR yet, but if they allowed setting custom headers (like User-Agent), there is no need to use any other third party library :)

**Comment by siberianguy** [comment]
Hey! Thanks for your answer. It's ironic how it just works in a JS version of SignalR client but in .NET it's a struggle. I've created an issue about custom headers in a repository with .NET Core version of SignalR: https://github.com/aspnet/SignalR/issues/1202 Let's see how it goes :)

**Comment by tompetko** [comment]
Yes, it's really pitty, they won't allow that. Anyway, I'll be watching this thread but for now, I'm closing this issue ;)

**Comment by siberianguy** [comment]
Good news :) SignalR .NET Core team responded yesterday: they do support custom headers

**Comment by tompetko** [comment]
The question is, if they support setting `User-Agent` header. In current .NET version, setting this header key results in error. If you manage to try that, please, let me know or reopen this issue :)

**Comment by siberianguy** [comment]
I started playing with it today. It looks promising but I still get an error. Shared the code here: https://github.com/elcattivo/CloudFlareUtilities/issues/18
