### ISSUE TITLE
Still getting 503 - Service Temporarily Unavailable

### ISSUE THREAD

**Issue by TeunKooijman** [tompetko/SignalR.WebSocketSharpTransport#2]
First of all a big thank you for writing up this package. Having to deal with CloudFlare on Bittrex myself would have been damn near impossible, so you've saved me a lot of headache and pain! 

I have implemented the functionality from your demo code, but sadly I am still getting a 503 - Service Temporarily Unavailable response from CloudFlare.  I was wondering if you had any hints or tips on trying to debug the issue.

Thanks in advance for any potential effort!

**Comment by TeunKooijman** [comment]
Seems like some namespaces where getting mixed up due to using `Microsoft.AspNet.SignalR.Core` as well as `Microsoft.AspNet.SignalR.Client`. Fixed the issue by using namespace aliases e.g.:

```
extern alias ClientSignalR;
extern alias CoreSignalR;

using ClientSignalR::Microsoft.AspNet.SignalR.Client;
using CoreSignalR::Microsoft.AspNet.SignalR.Core;

```

I've got it working now, thanks again for writing the package!

**Comment by tompetko** [comment]
Thank you @TeunKooijman! I'm glad, it's working :)
